[package]
name = "tcads-core"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Shared data structures, constants, and serialization logic for the TwinCAT ADS protocol"
keywords = ["twincat", "beckhoff", "ads"]
categories = ["api-bindings", "network-programming"]
readme = "README.md"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "net", "macros"] }
tokio-test = { workspace = true }
encoding_rs = { workspace = true }