[package]
name = "tcads"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tcads-core = { workspace = true }
tcads-client = { workspace = true }
tcads-server = { workspace = true }
thiserror = { workspace = true }
