[package]
name = "tcads-client"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tcads-core = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
